/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:5a879428-9163-4330-95cd-33a188a9c21c",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_5DY6lVAQZ",
    "aws_user_pools_web_client_id": "3ldtvkq3ej2kmck0o8r6bqec17",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "godrejdepositforms04f09-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
